[build-system]
# Defined by PEP 518
requires = [
  "setuptools>=64",
  "setuptools_scm[toml]>=7.0",
  "wheel",
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "lib/iris/_version.py"
local_scheme = "dirty-tag"
version_scheme = "release-branch-semver"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
(
  /(
    | sphinxext
    | tools
    | benchmarks\/\.asv.*
  )/
  | _ff_cross_references.py
  | um_cf_map.py
)
'''

[tool.isort]
force_sort_within_sections = "True"
known_first_party = "iris"
line_length = 79
profile = "black"
extend_skip = [
  "_build",
  "generated",
  "sphinxext",
  "tools",
]
skip_gitignore = "True"
verbose = "False"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = "lib/iris"

[tool.coverage.run]
branch = true
source = [
    "lib/iris",
]
omit = [
    "lib/iris/tests/*",
    "lib/iris/etc/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:"
]
