# Uses Github API to get a list of issues that have votes on and then
# update a gist with the results in json

name: Refresh Votable Issues

# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
  workflow_dispatch:
    inputs:
      clobber:
        description: "Force the workflow to run"
        default: "no"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run once daily at 02:30am
    - cron:  '30 02 * * *'


jobs:

  votable_main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

#      - uses: actions/script@v4
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            echo "hello world"
#            docs/src/query_gh_votable_issues.py ${{ secrets.GITHUB_TOKEN }}
#            cat votable-issues.json
