# Uses Github API to get a list of issues that have votes on and then
# update a gist with the results in json

name: refresh-votable-issues

on:
  workflow_dispatch:
    inputs:
      clobber:
        description: |
          Force the workflow to run, potentially clobbering any commits already made to the branch. 
          Enter "yes" or "true" to run.
        default: "no"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run once daily at 02:30am
    - cron:  '30 02 * * *'

jobs:
  votable_main:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - name: Fetch main
      - uses: actions/checkout@v2
        run: |
          git checkout HEAD

      - uses: actions/script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo "hello world"
            docs/src/query_gh_votable_issues.py ${{ secrets.GITHUB_TOKEN }}
            cat votable-issues.json
